### ISSUE TITLE
您好，请问topology有API文档或者使用说明吗？

### ISSUE THREAD

**Issue by sirxun** [zhaodabao/topology#6]
RT，谢谢您~！

**Comment by zhaodabao** [comment]
API文档要等后续的了，因为目前还没有完整的开源，代码都是压缩的，加之目前比较忙，后续随着代码陆续开源，文档也会补充的。另外，Topology是一个比较庞大的整体，可能您理解的API就类似于Topology中的图形引擎，这部分是比较有价值的，也的确抽象出了专门用于绘制拓扑结构的API。可能要请您再等等了O(∩_∩)O

**Comment by sirxun** [comment]
了解~很是期待呐~

**Comment by zhaodabao** [comment]
等忙过这段时间，我整理一下图形引擎并发布。如果您有邮件，我会通知第一时间通知您。感谢支持 :)

**Comment by luqin** [comment]
@zhaodabao 在这里回复就会通知当前issue的所有人

**Comment by Lujango** [comment]
+1
