### ISSUE TITLE
how to generate the eagle png from back-end?

### ISSUE THREAD

**Issue by yellox** [zhaodabao/topology#7]
I used php as the back-end script, is there any way to generate the eagle png with php dynamically? I am a noob on this kind of thing, could you give me some advice please?

**Comment by zhaodabao** [comment]
I have never used PHP script, topology eagle-eye map is generated with Batik.

Batik is a Java-based toolkit for applications or applets that want to use images in the Scalable Vector Graphics (SVG) format for various purposes, such as display, generation or manipulation.

Topology is based on Scalable Vector Graphics (SVG), and eagle-eye map also can be used as thumbnails, so we just use the Apache Batik toolkit. In fact, using the SVG &lt;use&gt; element is the simplest solution. The &lt;use&gt; element takes nodes from within the SVG document, and duplicates them somewhere else. In this way, the eagle-eye map can directly reference the main diagram.
